### PR TITLE
Refresh and missing locales

### PR DESCRIPTION
**Pull request by luisenrike**
Changed `I18n.t` to `Spree.t` (some missing translations errors)
Changed `FactoryGirl` to `FactoryBot`
Added a way to refresh or create documents

### CODE REVIEW

**Comment by luisenrike** [comment]
Added nil check

**Comment by rdehuyss** [comment]
When will this be integrated? What must happen to do so?

Currently, this is not really usable because of the missing translations...

**Comment by luisenrike** [comment]
Yeah, and it's a really good gem.

**Comment by imgarylai** [comment]
@damianlegawiec This PR can be closed. It is updated in #143 #145.

**Pull request closed without merging**
