### PR TITLE
Adds store pdf as file feature.

### PR DESCRIPTION
**Pull request by tvdeyen**
Introduces new settings `store_pdf` (disabled by default) and `storage_path` that allow to store the rendered pdf template to disk. These files can then be i.e. attached to emails.

Also refactors some tests and moves lots of code into the order model, away from the orders controller.

Refs #60

### CODE REVIEW

**Comment by tvdeyen** [comment]
BTW: 100% test coverage \o/

**Comment by tvdeyen** [comment]
Ah, dang! I broke the `update_invoice_number` feature. Closing.

**Comment by tvdeyen** [comment]
Ok, have to check the tests on travis. They pass locally. :disappointed:

**Comment by JDutil** [comment]
Probably because travis isn't giving you file system access

**Comment by tvdeyen** [comment]
@JDutil I fixed the specs

**Pull request closed without merging**
