### PR TITLE
Only include spree controller requests test helper in controller specs.

### PR DESCRIPTION
**Pull request by tvdeyen**
The test suite [is currently broken](https://travis-ci.org/spree-contrib/spree_print_invoice/jobs/54901249#L287)

### CODE REVIEW

**Comment by tvdeyen** [comment]
Build #34.1 stalled. Could someone please restart that? Thanks.

**Comment by JDutil** [comment]
@tvdeyen this extension needs new maintainers. If you'd be interested in commit access to this or other spree-contrib repos let me know.

**Comment by tvdeyen** [comment]
@JDutil hmm, I need to discuss this with my team. We have a bunch of work to do with Alchemy already, but yeah I will think about it. Could you just restart the [travis build](https://travis-ci.org/spree-contrib/spree_print_invoice/jobs/54905073) for now? Thanks.

**Comment by tvdeyen** [comment]
Thanks :+1:

**Comment by JDutil** [comment]
This was merged w/ 1c14220722bf3cd343a83a7a54b818bd0e944485

**Comment by JDutil** [comment]
@tvdeyen I should add we don't expect you to handle all the issues/prs, but you understand many of these spree-contrib projects well enough we can use additional maintainers to chip in whatever/whenever you can.

**Comment by tvdeyen** [comment]
Ok, add me :)

**Comment by tvdeyen** [comment]
Thanks for merging in.

**Comment by JDutil** [comment]
@tvdeyen I can either add you to whatever specific repos you want you all spree-contrib.  I'll start with just this repo, but if there are others you're also interested in let me know.

**Comment by tvdeyen** [comment]
spree_i18n ;)

https://github.com/spree-contrib/spree_i18n/issues/530

:D

**Comment by JDutil** [comment]
You've been added, but we should definitely discuss solution to https://github.com/spree-contrib/spree_i18n/issues/530 in PR or something first before pushing ;)

**Comment by tvdeyen** [comment]
Yes, for sure!

**Comment by tvdeyen** [comment]
@JDutil I know there is a spree Trello board. Maybe we should use this board (or a new one under that organistation) to discuss such "issues". Especially the voting feature is nice for such discussions.

My Trello account: tvdeyen (tvd@magiclabs.de)

**Pull request closed without merging**
